/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoadnt.ui;

import hoadnt.daos.ItemDao;
import hoadnt.daos.SupplierDao;
import hoadnt.dtos.ItemDTO;
import hoadnt.dtos.SuppplierDTO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author winnh
 */
public class ManageForm extends javax.swing.JFrame {
        Vector<String> ItemHeader = new Vector<>();
        Vector ItemData= new Vector();
        boolean addNew = true;
        final int SUCCESS = 1;

        Vector<String> SupHeader = new Vector<>();
        Vector Supdata = new Vector(); 
    /**
     * Creates new form ManageForm
     */
    public ManageForm() {
        initComponents();
        ItemHeader.add("Code");
        ItemHeader.add("Name");
        ItemHeader.add("Supplyer");
        ItemHeader.add("Unit");
        ItemHeader.add("Price");
        ItemHeader.add("supply");
        loadItemData();
        DefaultTableModel defaultModel;
        
//        CmbSupplying.removeAllItems();
//        
//            try {
//                for(SuppplierDTO Sup: SupplierDao.getAllSupplier()){
//                    CmbSupplying.addItem(Sup.getName());
//               
//                    
//                }   } catch (Exception ex) {
//                ex.printStackTrace();
//            }

        loadComboBox();

        defaultModel = (DefaultTableModel) tblItem.getModel();
        defaultModel.setDataVector(ItemData, ItemHeader);   
        
        SupHeader.add("SupCode");
        SupHeader.add("SupName");
        SupHeader.add("Address");
        SupHeader.add("Collobrating");
        
        loadSuppData();
        DefaultTableModel defaultModelSupp;
        defaultModelSupp=(DefaultTableModel) tblSupp.getModel();
        defaultModelSupp.setDataVector(Supdata, SupHeader);
    }
    void loadComboBox(){
        CmbSupplying.removeAllItems();
        try {
            for(SuppplierDTO Sup: SupplierDao.getAllSupplier()){
                String box=Sup.getName()+"-"+Sup.getCode();
                CmbSupplying.addItem(box);
             }
        } catch (Exception ex) {
                ex.printStackTrace();
        }
    }
    void loadItemData(){
        try{
           for (ItemDTO i: ItemDao.getAllItem()) {
               Vector row = new Vector();
                String supplying;
                if (i.isSupplying()) {
                    supplying = "true";
                } else {
                    supplying = "false";
                }               
               row.add(i.getCode());
               row.add(i.getName());
               row.add(i.getSupCode());
               row.add(i.getUnit());
               row.add(i.getPrice());
               row.add(supplying);
               ItemData.add(row);
           }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    void loadSuppData(){
        try{
            SupplierDao.checkCollaborating();
            for(SuppplierDTO s : SupplierDao.getAllSupplier()){
                Vector row= new Vector();
                String clb;
                if(s.isColloborate()) clb="true";
                else clb="false";
                row.add(s.getCode());
                row.add(s.getName());
                row.add(s.getAddress());
                row.add(clb);
                Supdata.add(row);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSuppCode = new javax.swing.JTextField();
        txtSuppName = new javax.swing.JTextField();
        txtSuppAddr = new javax.swing.JTextField();
        cbColl = new javax.swing.JCheckBox();
        btnAddSupp = new javax.swing.JButton();
        btnSaveSupp = new javax.swing.JButton();
        btnDelSupp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtitemName = new javax.swing.JTextField();
        CmbSupplying = new javax.swing.JComboBox<>();
        txtUnit = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbSupplier = new javax.swing.JCheckBox();
        btnAddItem = new javax.swing.JButton();
        btnSaveItem = new javax.swing.JButton();
        btnDelItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSupp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupp);

        jLabel1.setText("Code");

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel4.setText("Colloborating");

        btnAddSupp.setText("Add New");
        btnAddSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSuppActionPerformed(evt);
            }
        });

        btnSaveSupp.setText("Save");
        btnSaveSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSuppActionPerformed(evt);
            }
        });

        btnDelSupp.setText("Delete");
        btnDelSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSuppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSuppCode)
                                .addComponent(txtSuppName)
                                .addComponent(txtSuppAddr, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addComponent(cbColl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddSupp)
                        .addGap(27, 27, 27)
                        .addComponent(btnSaveSupp)
                        .addGap(26, 26, 26)
                        .addComponent(btnDelSupp)
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbColl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSupp)
                    .addComponent(btnSaveSupp)
                    .addComponent(btnDelSupp))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Suppplier", jPanel2);

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);

        jLabel5.setText("Item Code");

        jLabel6.setText("Item Name");

        jLabel7.setText("Supplier");

        jLabel8.setText("Unit");

        jLabel9.setText("Price");

        jLabel10.setText("Supplying");

        CmbSupplying.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbSupplying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSupplyingActionPerformed(evt);
            }
        });

        btnAddItem.setText("Add New");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnSaveItem.setText("Save");
        btnSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveItemActionPerformed(evt);
            }
        });

        btnDelItem.setText("Delete");
        btnDelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelItem))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(46, 46, 46)
                            .addComponent(txtPrice))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtItemCode)
                                .addComponent(txtitemName)
                                .addComponent(CmbSupplying, 0, 145, Short.MAX_VALUE)
                                .addComponent(txtUnit)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(24, 24, 24)
                            .addComponent(cbSupplier))))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtitemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbSupplying, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnSaveItem)
                    .addComponent(btnDelItem))
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Item", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmbSupplyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSupplyingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbSupplyingActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        addNew=false;
        txtItemCode.setEditable(false);
        int selectedRow = tblItem.getSelectedRow();
        String ItemCode= tblItem.getValueAt(selectedRow, 0).toString();
        String ItemName= tblItem.getValueAt(selectedRow, 1).toString();
        String supplyer =tblItem.getValueAt(selectedRow, 2).toString();
        String unit=tblItem.getValueAt(selectedRow, 3).toString();
        String price = tblItem.getValueAt(selectedRow, 4).toString();
        String supply= tblItem.getValueAt(selectedRow, 5).toString();
        txtItemCode.setText(ItemCode);
        txtitemName.setText(ItemName);
        txtUnit.setText(unit);
        txtPrice.setText(price);
        if(supply.equals("true")) cbSupplier.setSelected(true);
        else cbSupplier.setSelected(false);
        String supcode = "";
            try {
                supcode = SupplierDao.getSupByCode(supplyer)+"-"+supplyer;
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        CmbSupplying.setSelectedItem(supcode);
    }//GEN-LAST:event_tblItemMouseClicked

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        addNew=true;
        txtItemCode.setEditable(addNew);
        txtItemCode.requestFocus();
        txtItemCode.setText("");
        txtitemName.setText("");
        txtPrice.setText("");
        txtUnit.setText("");
        cbSupplier.setSelected(true);
        CmbSupplying.setSelectedItem(null);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveItemActionPerformed
        String itemCode= txtItemCode.getText().trim();
        String itemName= txtitemName.getText().trim();
        String supplierName= CmbSupplying.getSelectedItem().toString().trim();
        String unit=txtUnit.getText().trim();
        String priceStr=txtPrice.getText().trim();
        boolean supplying= cbSupplier.isSelected(); 
        if(itemCode.isEmpty()){
            JOptionPane.showMessageDialog(this, "Code is not null!!!");
            return;
        }
        if(itemName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Name is not null!!!");
            return;
        }        
        try{
                String supplierCode= SupplierDao.getSupCodeByName(supplierName);
                if(priceStr.matches(".*[a-zA-Z].*")){
                    JOptionPane.showMessageDialog(this, "Price is a positive Number!!!");
                    return;
                }
                if(priceStr.matches(".*-{1,}.*")){
                    JOptionPane.showMessageDialog(this, "Price  is a positive Number!!!");
                    return;
                }
                float price= Float.valueOf(txtPrice.getText().trim());
                ItemDTO item= new ItemDTO(itemCode, itemName, supplierCode, price, unit, supplying);
                if(addNew){
                    try{

                        if(!ItemDao.getItemByCode(itemCode).isEmpty()){
                            JOptionPane.showMessageDialog(this, "Code is duplicated");
                             return;
                        }
                        if(ItemDao.insert(item)==SUCCESS){
                            Vector row = new Vector();
                            row.add(itemCode);
                            row.add(itemName);
                            row.add(supplierCode);
                            row.add(unit);
                            row.add(price);
                            row.add(supplying);
                            ItemData.add(row);
                            tblItem.updateUI();
                        }
                    }catch(Exception ex){
                        ex.printStackTrace();
                    }
                } else{
                    try{
                        if(ItemDao.update(item)==SUCCESS){
                            int selectedRow=tblItem.getSelectedRow();
                            Vector row=(Vector) ItemData.get(selectedRow);
                            row.set(1, itemName);
                            row.set(2,supplierCode);
                            row.set(3, unit);
                            row.set(4, price);
                            row.set(5, supplying);
                            tblItem.updateUI();
                        }
                    } catch(Exception e){
                        e.printStackTrace();
                    }

           
            }
            SupplierDao.checkCollaborating();
            Supdata.clear();
            loadSuppData();
            tblSupp.updateUI();
        }catch(Exception ee){
            ee.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveItemActionPerformed

    private void btnDelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelItemActionPerformed
        int r= JOptionPane.showConfirmDialog(this, "Are you sure?","Remove?",JOptionPane.YES_NO_OPTION);
        if(r==JOptionPane.YES_OPTION);
        if(r== JOptionPane.YES_OPTION){
            try{
                int selectedRow= tblItem.getSelectedRow();
                String itemCode= tblItem.getValueAt(selectedRow, 0).toString();
                if(ItemDao.delete(itemCode)==SUCCESS){
                    ItemData.remove(selectedRow);
                    tblItem.updateUI();
                    SupplierDao.checkCollaborating();
                    Supdata.clear();
                    loadSuppData();
                    tblSupp.updateUI();
                }
            }catch(Exception ee){
                ee.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDelItemActionPerformed

    private void btnAddSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSuppActionPerformed
        addNew=true;
        txtSuppCode.setEditable(addNew);
        txtSuppCode.setText("");
        txtSuppName.setText("");
        txtSuppAddr.setText("");
        txtSuppCode.requestFocus();
    }//GEN-LAST:event_btnAddSuppActionPerformed

    private void tblSuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppMouseClicked
        addNew=false;
        txtSuppCode.setEditable(addNew);
        int selectedRow= tblSupp.getSelectedRow();
        String code= tblSupp.getValueAt(selectedRow, 0).toString();
        String name= tblSupp.getValueAt(selectedRow, 1).toString();
        String address= tblSupp.getValueAt(selectedRow, 2).toString();
        boolean clb=Boolean.valueOf(tblSupp.getValueAt(selectedRow, 3).toString());
        txtSuppCode.setText(code);
        txtSuppName.setText(name);
        txtSuppAddr.setText(address);
        cbColl.setSelected(clb);
    }//GEN-LAST:event_tblSuppMouseClicked

    private void btnSaveSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSuppActionPerformed
        String code= txtSuppCode.getText().trim();
        String name= txtSuppName.getText().trim();
        String address= txtSuppAddr.getText().trim();
        boolean clb= cbColl.isSelected();
        SuppplierDTO sup= new SuppplierDTO(code, name, address, clb);
        if(code.isEmpty()){
            JOptionPane.showMessageDialog(this, "Code is not null!!");
            return;
        }
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Name is not null!!!");
            return;
        }
        if(addNew){
            try{
                if(!SupplierDao.getSupByCode(code).isEmpty()){
                    JOptionPane.showMessageDialog(this, "Code is duplicated");
                    return;
                }
                if(SupplierDao.insert(sup) ==SUCCESS){
                    Vector row = new Vector();
                    row.add(code);
                    row.add(name);
                    row.add(address);
                    row.add(String.valueOf(clb));
                    Supdata.add(row);
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
        } else{
            try{
                if(SupplierDao.update(sup)==SUCCESS){
                    int selectedRow= tblSupp.getSelectedRow();
                    Vector row= (Vector) Supdata.get(selectedRow);
                    row.set(1, name);
                    row.set(2, address);
                    row.set(3, clb);
                }
            }catch(Exception ee){
                ee.printStackTrace();
            }
        }
        tblSupp.updateUI();
        loadComboBox();
       
    }//GEN-LAST:event_btnSaveSuppActionPerformed

    private void btnDelSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSuppActionPerformed

         int r=JOptionPane.showConfirmDialog(this, "Are you sure?", "Remove", JOptionPane.YES_NO_OPTION);
         if(r ==JOptionPane.YES_OPTION){
             try{
                 int selectedRow= tblSupp.getSelectedRow();
                 String suppCode= tblSupp.getValueAt(selectedRow, 0).toString();
                 boolean supplying=Boolean.parseBoolean(tblSupp.getValueAt(selectedRow,3).toString());
                if(supplying==true){
                    JOptionPane.showMessageDialog(this, "Supplier is supplying");
                    return;
                }else{
                    SupplierDao dao= new SupplierDao();
                    if(dao.delete(suppCode)==SUCCESS){
                        Supdata.remove(selectedRow);
                        tblSupp.updateUI();
                    }
                    
                }
                loadComboBox();
                tblItem.updateUI();
                    
             }catch (Exception e){
                  e.printStackTrace();
             }
         }
    }//GEN-LAST:event_btnDelSuppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbSupplying;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAddSupp;
    private javax.swing.JButton btnDelItem;
    private javax.swing.JButton btnDelSupp;
    private javax.swing.JButton btnSaveItem;
    private javax.swing.JButton btnSaveSupp;
    private javax.swing.JCheckBox cbColl;
    private javax.swing.JCheckBox cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblSupp;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSuppAddr;
    private javax.swing.JTextField txtSuppCode;
    private javax.swing.JTextField txtSuppName;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txtitemName;
    // End of variables declaration//GEN-END:variables
}
